import { useRef, useState } from "react";
import { ArrowRight, Camera, ChefHat, CircleGauge, Clock3, CookingPot, Play, RefreshCw, Search, Sparkles, Timer, Utensils } from "lucide-react";
import { Link } from "react-router-dom";
import hero from "../assets/hero-food.jpg";
import phoneFood from "../assets/smoothie-bowl.jpg";
import { RecipeCard } from "../components/RecipeCard";
import { categories, recipes } from "../data/recipes";
import { assistantAnswer, rankRecipes } from "../services/kitchen";

export function HomePage(){
  const [ingredients,setIngredients]=useState<string[]>(["Tomato","Rice"]); const [entry,setEntry]=useState(""); const [matched,setMatched]=useState(false);
  const [question,setQuestion]=useState(""); const [answer,setAnswer]=useState("Ask me about substitutions, timing, servings, or storage."); const fileRef=useRef<HTMLInputElement>(null); const [scan,setScan]=useState("");
  const add=()=>{const value=entry.trim();if(value&&!ingredients.some(i=>i.toLowerCase()===value.toLowerCase()))setIngredients([...ingredients,value]);setEntry("")};
  const results=rankRecipes(recipes,ingredients);
  return <>
    <section className="hero section"><div className="hero-copy"><div className="pill"><Sparkles/>Smart cooking starts here</div><h1>Cook better. Eat smarter. <em>Enjoy every bite.</em></h1><p>Discover recipes for what you have, plan the week, and get a little help exactly when you need it.</p><div className="actions"><Link className="primary" to="/recipes">Explore recipes <ArrowRight/></Link><a className="secondary" href="#ask">Ask Yummy</a></div><div className="proof"><b>5,000+</b> kitchen-tested ideas <span/> <b>4.9</b> cook rating</div></div><div className="hero-visual"><div className="sun-shape"/><img src={hero} alt="A colorful, nourishing meal bowl" width="720" height="720"/><span className="float-chip one"><Clock3/>30 min meal</span><span className="float-chip two"><CircleGauge/>High protein</span><span className="float-chip three"><ChefHat/>Easy recipe</span></div></section>

    <section className="section"><div className="section-heading"><div><span className="kicker">Fresh inspiration</span><h2>Featured recipes</h2></div><Link to="/recipes">See all recipes <ArrowRight/></Link></div><div className="card-grid">{recipes.slice(0,3).map(r=><RecipeCard key={r.id} recipe={r}/>)}</div></section>

    <section className="section ingredient-lab" id="ingredients"><div><span className="kicker">Use what you have</span><h2>What can I cook?</h2><p>Turn a few ingredients into a meal worth looking forward to.</p><div className="tag-input"><div className="tags">{ingredients.map(i=><button key={i} onClick={()=>setIngredients(ingredients.filter(x=>x!==i))}>{i} ×</button>)}</div><div className="input-row"><input value={entry} onChange={e=>setEntry(e.target.value)} onKeyDown={e=>e.key==="Enter"&&add()} placeholder="Try chicken, tomato, rice…" aria-label="Ingredient"/><button className="secondary" onClick={add}>Add</button></div></div><div className="actions"><button className="primary" onClick={()=>setMatched(true)}><Search/>Find recipes</button><button className="secondary" onClick={()=>fileRef.current?.click()}><Camera/>Scan ingredients</button><input ref={fileRef} hidden type="file" accept="image/*" onChange={e=>{if(e.target.files?.[0]){setScan("Demo scan: tomato, spinach and eggs detected");setIngredients(["Tomato","Spinach","Eggs"])}}}/></div>{scan&&<p className="notice">{scan}. Detection is a preview demonstration.</p>}</div><div className="match-results"><h3>{matched?`${results.length} tasty matches`:"Your best matches will appear here"}</h3>{(matched?results.slice(0,3):rankRecipes(recipes,ingredients).slice(0,2)).map(({recipe,matches})=><Link to={`/recipes/${recipe.id}`} className="mini-result" key={recipe.id}><img src={recipe.image} alt="" width="90" height="90"/><span><b>{recipe.title}</b><small>{matches} ingredient{matches===1?"":"s"} matched · {recipe.time} min</small></span><ArrowRight/></Link>)}</div></section>

    <section className="section"><div className="section-heading"><div><span className="kicker">Find your flavor</span><h2>Explore categories</h2></div></div><div className="category-grid">{categories.map((c,i)=><Link key={c} to={`/recipes?filter=${encodeURIComponent(c)}`} className={`category c${i%5}`}><span>{["🍳","🥗","🍛","🥪","🍰"][i%5]}</span>{c}</Link>)}</div></section>

    <section className="section ask" id="ask"><div className="ask-copy"><div className="pill dark"><Sparkles/>Local kitchen helper</div><h2>Stuck mid-recipe?<br/>Ask Yummy.</h2><p>Quick, practical guidance while your hands are busy.</p><div className="quick-prompts">{["What can I use instead of eggs?","How long should I bake this?","Adjust this recipe for six people","How should I store leftovers?"].map(q=><button key={q} onClick={()=>{setQuestion(q);setAnswer(assistantAnswer(q))}}>{q}</button>)}</div></div><div className="assistant-box"><div className="assistant-answer"><span className="bot"><ChefHat/></span><p>{answer}</p></div><div className="input-row"><input value={question} onChange={e=>setQuestion(e.target.value)} onKeyDown={e=>e.key==="Enter"&&setAnswer(assistantAnswer(question))} placeholder="Ask a cooking question…"/><button className="primary" onClick={()=>setAnswer(assistantAnswer(question))}>Ask</button></div><small>Answers use built-in cooking guidance and do not contact an AI service.</small></div></section>

    <section className="section split-feature"><div className="feature-collage"><img src={phoneFood} alt="Fresh breakfast bowl shown in Yummy" width="640" height="720" loading="lazy"/><span><Play fill="currentColor"/>Cook step by step</span></div><div><span className="kicker">Plan once, relax all week</span><h2>Your week, deliciously organized.</h2><p>Build a meal plan, turn it into one tidy grocery list, and understand the nutrition at a glance.</p><div className="feature-list"><Link to="/planner"><RefreshCw/><span><b>Smart weekly planner</b><small>Seven days, tailored to your preferences</small></span></Link><Link to="/grocery"><CookingPot/><span><b>One-tap grocery list</b><small>Grouped, combined, and easy to check off</small></span></Link><Link to="/tools"><Timer/><span><b>Tools that actually help</b><small>Converters, timers, storage and substitutes</small></span></Link></div></div></section>

    <section className="section"><div className="section-heading"><div><span className="kicker">Loved this week</span><h2>Popular with home cooks</h2></div></div><div className="card-grid">{recipes.slice(3,6).map(r=><RecipeCard key={r.id} recipe={r}/>)}</div></section>

    <section className="section collection"><div><span className="kicker">Keep exploring</span><h2>Recipe collections</h2></div><div className="collection-grid">{["Meals under 30 minutes","Healthy breakfasts","High protein favorites","Dinner for two","Budget-friendly meals","Weekend cooking"].map((x,i)=><Link key={x} to="/recipes" className={`collection-card collection-${i}`}><Utensils/><span>{x}</span><ArrowRight/></Link>)}</div></section>

    <section className="section tips"><div className="section-heading"><div><span className="kicker">Know-how for every cook</span><h2>Kitchen tips & guides</h2></div></div><div className="tips-grid">{[["Knife skills","Cut more safely and consistently."],["Seasoning basics","Build flavor with confidence."],["Baking tips","Better texture, rise and color."],["Cooking meat","Doneness without the guesswork."],["Food storage","Keep ingredients fresher longer."],["Meal prep","Make busy days feel effortless."]].map(([t,d],i)=><article key={t}><span>{["🔪","🧂","🥐","🍗","🫙","🥕"][i]}</span><h3>{t}</h3><p>{d}</p><Link to="/tools">Learn more</Link></article>)}</div></section>
  </>;
}
