import{ArrowRight,Clock3,MapPin,Search,Sparkles,Utensils}from"lucide-react";import{useState}from"react";import{Link,useNavigate}from"react-router-dom";import hero from"../assets/hero-food.jpg";import{DishCard}from"../components/DishCard";import{RestaurantCard}from"../components/RestaurantCard";import{cuisines,restaurants}from"../data/delivery";import{useDelivery}from"../hooks/useDeliveryState";
export function HomePage(){const{location,setLocation}=useDelivery();const[query,setQuery]=useState("");const nav=useNavigate();const search=(e:React.FormEvent)=>{e.preventDefault();nav(`/restaurants?q=${encodeURIComponent(query)}`)};const dishes=restaurants.flatMap(r=>r.dishes.map(d=>({d,r})));return <>
<section className="delivery-hero"><div className="delivery-hero-bg"><img src={hero} alt="" width="1400" height="700"/></div><div className="delivery-hero-content"><span className="kicker">Yummy Delivery</span><h1>Good food,<br/><em>right to your door.</em></h1><p>Discover trusted restaurants, comforting favorites and exciting new flavors near you.</p><div className="delivery-locator"><label><MapPin/><span><small>Delivering to</small><select value={location} onChange={e=>setLocation(e.target.value)}><option>Green Park, New Delhi</option><option>Hauz Khas, New Delhi</option><option>Cyber City, Gurugram</option><option>Indiranagar, Bengaluru</option></select></span></label><form onSubmit={search}><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search restaurants, dishes or cuisines"/><button>Search</button></form></div><div className="hero-badges"><span><Clock3/>30 minute favorites</span><span><Sparkles/>Handpicked offers</span></div></div></section>
<section className="section delivery-section"><div className="section-heading"><div><span className="kicker">What are you craving?</span><h2>Eat what makes you happy</h2></div></div><div className="cuisine-scroll">{cuisines.map((c,i)=><Link to={`/restaurants?q=${encodeURIComponent(c)}`} key={c}><span>{["🍕","🍲","🍔","🥡","🍛","🥞","🍰","🥗","🌯","🥟"][i]}</span><b>{c}</b></Link>)}</div></section>
<section className="section delivery-section offers-home"><div className="section-heading"><div><span className="kicker">Big flavor, better value</span><h2>Offers for you</h2></div><Link to="/offers">View all <ArrowRight/></Link></div><div className="offer-grid"><Link to="/restaurants" className="offer-card red"><small>WELCOME OFFER</small><b>20% OFF</b><span>Use code YUMMY20</span></Link><Link to="/restaurants" className="offer-card green"><small>ZERO DELIVERY FEE</small><b>FREEDEL</b><span>On participating restaurants</span></Link><Link to="/restaurants/spice-route" className="offer-card yellow"><small>THE SPICE ROUTE</small><b>₹120 OFF</b><span>On your comfort-food fix</span></Link></div></section>
<RestaurantSection title="Restaurants near you" kicker={location} list={restaurants}/><RestaurantSection title="Top rated restaurants" kicker="Loved by your neighborhood" list={[...restaurants].sort((a,b)=>b.rating-a.rating).slice(0,3)}/>
<section className="section delivery-section"><div className="section-heading"><div><span className="kicker">Trending near you</span><h2>Popular dishes</h2></div><Link to="/restaurants">Explore all <ArrowRight/></Link></div><div className="dish-home-grid">{dishes.filter(x=>x.d.bestseller).map(({d,r})=><DishCard key={d.id} dish={d} restaurant={r}/>)}</div></section>
<RestaurantSection title="Fast delivery" kicker="At your door in about 30 minutes" list={[...restaurants].sort((a,b)=>a.deliveryMinutes-b.deliveryMinutes).slice(0,3)}/>
<section className="section kitchen-promo"><div><span className="kicker">Yummy Kitchen</span><h2>Sometimes, the best table is your own.</h2><p>Discover recipes, plan meals, build grocery lists and get practical cooking help.</p><Link className="primary" to="/kitchen/recipes"><Utensils/>Explore Yummy Kitchen</Link></div><div className="kitchen-stats"><span><b>6</b> kitchen-tested recipes</span><span><b>7</b> days planned in seconds</span><span><b>5</b> practical cooking tools</span></div></section>
<section className="section app-promo"><div><span className="kicker">Yummy everywhere</span><h2>Your cravings,<br/>one tap away.</h2><p>Save favorites, track orders and plan your next meal from any screen.</p><div className="actions"><Link className="primary" to="/restaurants">Order now</Link><Link className="secondary" to="/orders">Track an order</Link></div></div><div className="phone-mock"><span>Yummy</span><img src={hero} alt="Yummy mobile food discovery preview" width="360" height="500"/><b>Hungry? We’ve got you.</b></div></section></>}
function RestaurantSection({title,kicker,list}:{title:string;kicker:string;list:typeof restaurants}){return <section className="section delivery-section"><div className="section-heading"><div><span className="kicker">{kicker}</span><h2>{title}</h2></div><Link to="/restaurants">See all <ArrowRight/></Link></div><div className="restaurant-grid">{list.map(r=><RestaurantCard key={r.id} restaurant={r}/>)}</div></section>}
