import { Calculator, Clock3, Container, RefreshCcw, Search, Thermometer, TimerReset, Users } from "lucide-react";
import { useEffect, useState } from "react";
import { assistantAnswer, convertMeasurement, convertTemperature } from "../services/kitchen";
export function ToolsPage(){
 const [measure,setMeasure]=useState({value:1,from:"cup",to:"ml"}); const [temp,setTemp]=useState({value:180,from:"C" as "C"|"F"}); const [servings,setServings]=useState(4); const [seconds,setSeconds]=useState(0); const [running,setRunning]=useState(false); const [sub,setSub]=useState("");
 useEffect(()=>{if(!running||seconds<=0)return;const id=window.setInterval(()=>setSeconds(s=>{if(s<=1){setRunning(false);return 0}return s-1}),1000);return()=>clearInterval(id)},[running,seconds]);
 const units=["g","kg","oz","lb","ml","l","cup","tbsp","tsp"];
 return <section className="section page"><div className="page-heading"><span className="kicker">Useful answers, right on time</span><h1>Kitchen tools</h1><p>Convert, scale, time and store with less guesswork.</p></div><div className="tools-grid"><Tool icon={<Calculator/>} title="Measurement converter"><div className="tool-line"><input type="number" value={measure.value} onChange={e=>setMeasure({...measure,value:+e.target.value})}/><select value={measure.from} onChange={e=>setMeasure({...measure,from:e.target.value})}>{units.map(u=><option key={u}>{u}</option>)}</select><RefreshCcw/><select value={measure.to} onChange={e=>setMeasure({...measure,to:e.target.value})}>{units.map(u=><option key={u}>{u}</option>)}</select></div><output>{convertMeasurement(measure.value,measure.from,measure.to).toFixed(2)} {measure.to}</output></Tool><Tool icon={<Thermometer/>} title="Temperature converter"><div className="tool-line"><input type="number" value={temp.value} onChange={e=>setTemp({...temp,value:+e.target.value})}/><select value={temp.from} onChange={e=>setTemp({...temp,from:e.target.value as "C"|"F"})}><option>C</option><option>F</option></select></div><output>{convertTemperature(temp.value,temp.from).toFixed(1)}°{temp.from==="C"?"F":"C"}</output></Tool><Tool icon={<Users/>} title="Serving size adjuster"><p>Original recipe: 4 servings</p><input type="range" min="1" max="12" value={servings} onChange={e=>setServings(+e.target.value)}/><output>{servings} servings · multiply by {(servings/4).toFixed(2)}</output></Tool><Tool icon={<Clock3/>} title="Multi-timer"><div className="timer-display">{Math.floor(seconds/60)}:{String(seconds%60).padStart(2,"0")}</div><div className="actions"><button className="secondary" onClick={()=>{setSeconds(300);setRunning(true)}}>5 min</button><button className="secondary" onClick={()=>{setSeconds(600);setRunning(true)}}>10 min</button><button className="secondary" onClick={()=>setRunning(!running)}>{running?"Pause":"Start"}</button><button className="icon-button" onClick={()=>{setSeconds(0);setRunning(false)}}><TimerReset/></button></div></Tool><Tool icon={<Container/>} title="Food storage guide"><div className="guide-list"><span><b>Cooked rice</b>3–4 days chilled</span><span><b>Raw chicken</b>1–2 days chilled</span><span><b>Leafy greens</b>5–7 days chilled</span><span><b>Soup</b>3–4 days chilled</span></div></Tool><Tool icon={<Search/>} title="Substitute finder"><input value={sub} onChange={e=>setSub(e.target.value)} placeholder="What do you need to replace?"/><output>{sub?assistantAnswer(`substitute ${sub}`):"Enter an ingredient for a practical alternative."}</output></Tool></div><div className="storage-strip"><span>🫙</span><div><h2>Expiry tracker</h2><p>Add dates to your grocery list and check food before relying on a date alone. When in doubt, throw it out.</p></div><a className="secondary" href="/grocery">Open groceries</a></div></section>
}
function Tool({icon,title,children}:{icon:React.ReactNode;title:string;children:React.ReactNode}){return <article className="tool-card"><header><span>{icon}</span><h2>{title}</h2></header>{children}</article>}
